version: "3.8"
services:
  web:
    image: romeo0245/web-focusify
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: always
    # env for github action
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_ENDPOINT
      - NEXT_PUBLIC_PROJECT
    # nginx
  nginx:
    image: nginx:1.17.1-alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - /ssl:/etc/nginx/ssl:ro
    depends_on:
      - web