import dynamic from "next/dynamic";
import WallpaperMain from "./components/wallpaper/main";
const MainList = dynamic(() => import("./components/menu/mainList"), {
  ssr: false,
});

const ControlComponents = dynamic(
  () => import("./controller/controlComponents"),
  {
    ssr: false,
  }
);

export const metadata = {
  title: "Focusify",
  description: "Generated by create next app",
};

const AppFocusPage = () => {
  return (
    <div className="w-screen h-screen relative overflow-hidden">
      {/* menu */}
      <MainList />
      {/* dragable */}
      <ControlComponents />

      <WallpaperMain />
    </div>
  );
};

export default AppFocusPage;
