import "./globals.scss";
import { Inter } from "next/font/google";
import { Providers } from "./redux/provider";
import { AlertProvider } from "./hook/AlertContext";
import MotionAlert from "./hook/MotionAlert";
import ToastAlert from "./hook/ToastAlert";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true} className={inter.className}>
        <AlertProvider>
          <Providers>{children}</Providers>
          <MotionAlert />
          <ToastAlert />
        </AlertProvider>
      </body>
    </html>
  );
}
