name: remote ssh command
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker images
      env:
        NEXT_PUBLIC_ENDPOINT: ${{ secrets.NEXT_PUBLIC_ENDPOINT }}
        NEXT_PUBLIC_PROJECT: ${{ secrets.NEXT_PUBLIC_PROJECT }}
      run: |
        echo NEXT_PUBLIC_ENDPOINT=$NEXT_PUBLIC_ENDPOINT >> .env
        echo NEXT_PUBLIC_PROJECT=$NEXT_PUBLIC_PROJECT >> .env
        cat .env
        docker-compose build --no-cache
        docker-compose push

    - name: Logout of Docker Hub
      run: docker logout

  deploy:
    needs: build
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        command_timeout: 20m
        script: |
          cd focusify/
          git pull origin master
          docker-compose down -v
          docker-compose pull
          docker-compose up -d